"use strict"

const typeColorsCSS = {
    "normal": {
        default:"#C6C6A7",
        hover: "#A8A878",
        selected: "#6D6D4E"
    },
    "fire": {
        default:"#F5AC78",
        hover: "#F08030",
        selected: "#9C531F"
    },
    "water": {
        default:"#9DB7F5",
        hover: "#6890F0",
        selected: "#445E9C"
    },
    "electric": {
        default:"#FAE078",
        hover: "#F8D030",
        selected: "#A1871F"
    },
    "grass": {
        default:"#A7DB8D",
        hover: "#78C850",
        selected: "#4E8234"
    },
    "ice": {
        default:"#BCE6E6",
        hover: "#98D8D8",
        selected: "#638D8D"
    },
    "fighting": {
        default:"#D67873",
        hover: "#C03028",
        selected: "#7D1F1A "
    },
    "poison": {
        default:"#C183C1",
        hover: "#A040A0",
        selected: "#682A68"
    },
    "ground": {
        default:"#EBD69D",
        hover: "#E0C068",
        selected: "#927D44"
    },
    "flying": {
        default:"#C6B7F5",
        hover: "#A890F0",
        selected: "#6D5E9C"
    },
    "psychic": {
        default:"#FA92B2",
        hover: "#F85888",
        selected: "#A13959"
    },
    "bug": {
        default:"#C6D16E",
        hover: "#A8B820",
        selected: "#6D7815"
    },
    "rock": {
        default:"#D1C17D",
        hover: "#B8A038",
        selected: "#786824"
    },
    "ghost": {
        default:"#A292BC",
        hover: "#705898",
        selected: "#493963"
    },
    "dragon": {
        default:"#A27DFA",
        hover: "#7038F8",
        selected: "#4924A1"
    },
    "dark": {
        default:"#A29288",
        hover: "#705848",
        selected: "#49392F"
    },
    "steel": {
        default:"#D1D1E0",
        hover: "#B8B8D0",
        selected: "#787887"
    },
    "fairy": {
        default:"#F4BDC9",
        hover: "#EE99AC",
        selected: "#9B6470"
    },
}

const pkTypeRelations = {
    "normal": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 2,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 0,
      "dragon": 1,
      "dark": 1,
      "steel": 1,
      "fairy": 1
    },
    "fire": {
      "normal": 1,
      "fire": 0.5,
      "water": 2,
      "electric": 1,
      "grass": 0.5,
      "ice": 0.5,
      "fighting": 1,
      "poison": 1,
      "ground": 2,
      "flying": 1,
      "psychic": 1,
      "bug": 0.5,
      "rock": 2,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 0.5      
    },
    "water": {
      "normal": 1,
      "fire": 0.5,
      "water": 0.5,
      "electric": 2,
      "grass": 2,
      "ice": 0.5,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1
    },
    "electric": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 0.5,
      "grass": 1,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 2,
      "flying": 0.5,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 0.5,
      "fairy": 1
    },
    "grass": {
      "normal": 1,
      "fire": 2,
      "water": 0.5,
      "electric": 0.5,
      "grass": 0.5,
      "ice": 2,
      "fighting": 1,
      "poison": 2,
      "ground": 0.5,
      "flying": 2,
      "psychic": 1,
      "bug": 2,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 1,
      "fairy": 1
    },
    "ice": {
      "normal": 1,
      "fire": 2,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 0.5,
      "fighting": 2,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 2,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 2,
      "fairy": 1
    },
    "fighting": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 2,
      "psychic": 2,
      "bug": 0.5,
      "rock": 0.5,
      "ghost": 1,
      "dragon": 1,
      "dark": 0.5,
      "steel": 1,
      "fairy": 2
    },
    "poison": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 0.5,
      "ice": 1,
      "fighting": 0.5,
      "poison": 0.5,
      "ground": 2,
      "flying": 1,
      "psychic": 2,
      "bug": 0.5,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 1,
      "fairy": 0.5
    },
    "ground": {
      "normal": 1,
      "fire": 1,
      "water": 2,
      "electric": 0,
      "grass": 2,
      "ice": 2,
      "fighting": 1,
      "poison": 0.5,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 0.5,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 1,
      "fairy": 1
    },
    "flying": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 2,
      "grass": 0.5,
      "ice": 2,
      "fighting": 0.5,
      "poison": 1,
      "ground": 0,
      "flying": 1,
      "psychic": 1,
      "bug": 0.5,
      "rock": 2,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 1,
      "fairy": 1
    },
    "psychic": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 0.5,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 0.5,
      "bug": 2,
      "rock": 1,
      "ghost": 2,
      "dragon": 1,
      "dark": 2,
      "steel": 1,
      "fairy": 1
    },
    "bug": {
      "normal": 1,
      "fire": 2,
      "water": 1,
      "electric": 1,
      "grass": 0.5,
      "ice": 1,
      "fighting": 0.5,
      "poison": 1,
      "ground": 0.5,
      "flying": 2,
      "psychic": 1,
      "bug": 1,
      "rock": 2,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 1,
      "fairy": 1
    },
    "rock": {
      "normal": 0.5,
      "fire": 0.5,
      "water": 2,
      "electric": 1,
      "grass": 2,
      "ice": 1,
      "fighting": 2,
      "poison": 0.5,
      "ground": 2,
      "flying": 0.5,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 1,
      "dark": 1,
      "steel": 2,
      "fairy": 1
    },
    "ghost": {
      "normal": 0,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 0,
      "poison": 0.5,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 0.5,
      "rock": 1,
      "ghost": 2,
      "dragon": 1,
      "dark": 2,
      "steel": 1,
      "fairy": 1
    },
    "dragon": {
      "normal": 1,
      "fire": 0.5,
      "water": 0.5,
      "electric": 0.5,
      "grass": 0.5,
      "ice": 2,
      "fighting": 1,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 1,
      "rock": 1,
      "ghost": 1,
      "dragon": 2,
      "dark": 1,
      "steel": 1,
      "fairy": 2
    },
    "dark": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 2,
      "poison": 1,
      "ground": 1,
      "flying": 1,
      "psychic": 0,
      "bug": 2,
      "rock": 1,
      "ghost": 0.5,
      "dragon": 1,
      "dark": 0.5,
      "steel": 1,
      "fairy": 2
    },
    "steel": {
      "normal": 0.5,
      "fire": 2,
      "water": 1,
      "electric": 1,
      "grass": 0.5,
      "ice": 0.5,
      "fighting": 2,
      "poison": 0,
      "ground": 2,
      "flying": 0.5,
      "psychic": 0.5,
      "bug": 0.5,
      "rock": 0.5,
      "ghost": 1,
      "dragon": 0.5,
      "dark": 1,
      "steel": 0.5,
      "fairy": 0.5
    },
    "fairy": {
      "normal": 1,
      "fire": 1,
      "water": 1,
      "electric": 1,
      "grass": 1,
      "ice": 1,
      "fighting": 0.5,
      "poison": 2,
      "ground": 1,
      "flying": 1,
      "psychic": 1,
      "bug": 0.5,
      "rock": 1,
      "ghost": 1,
      "dragon": 0,
      "dark": 0.5,
      "steel": 2,
      "fairy": 1
    }
}